name: nf-core-nascent-1.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.5
  - multiqc=1.6
  - hisat2=2.1.0
  - samtools=1.8
  - preseq=2.0.3
  - seqkit=0.9.0
  - bedtools=2.25.0
  - igvtools=2.3.75
  - bbmap=38.06
  - fastx_toolkit=0.0.14
  - sra-tools=2.9.1
  - rseqc=3.0.0
